### ISSUE TITLE
support android build for quic

### ISSUE THREAD

**Issue by cthulhu-irl** [WolfEngine/wolf#13]
Currently the `msquic` dependency used by this library is only to support windows.

The android support is needed.

**Comment by PooyaEimandar** [comment]
waiting for [this merge](https://github.com/microsoft/vcpkg/pull/29568)

**Comment by cthulhu-irl** [comment]
for the time being, https://github.com/WolfEngine/wolf-deps/ will be used instead of vcpkg.
