### ISSUE TITLE
use vcpkg root path to execute vcpkg command

### ISSUE THREAD

**Issue by cthulhu-irl** [WolfEngine/wolf#15]
vcpkg from `PATH` (default invocation) can have different root from `VCPKG_ROOT` environment path, which on invocation of an installation command for example the package will be installed in a different root than defined by `VCPKG_ROOT`.

this mismatch is warned and logged in ci jobs too: https://github.com/WolfEngine/wolf/actions/runs/5076359070/jobs/9118461224#step:5:64

it is due to using the cmake toolchain file from `VCPKG_ROOT`, while `vcpkg` command that is invoked in the cmake configurations to install some packages resides in a different root.

this can be fixed by invoking `VCPKG_ROOT/vcpkg` instead. (define a `VCPKG_PROGRAM` in cmake for this purpose)

**Comment by PooyaEimandar** [comment]
[fixed](https://github.com/WolfEngine/wolf/blob/24a6e3e5c5c0910b36507e93ddca5670170576c1/wolf/cmake/vcpkg.cmake#L5)
