### ISSUE TITLE
suspecting a memory leak and crash related to QUIC test

### ISSUE THREAD

**Issue by PooyaEimandar** [WolfEngine/wolf#16]
suspecting a memory leak and crash related to this [test](https://github.com/WolfEngine/wolf/blob/24a6e3e5c5c0910b36507e93ddca5670170576c1/wolf/stream/test/quic.hpp#L24)

**Comment by cthulhu-irl** [comment]
It is expected to be automatically fixed by this feature and refactoring the codebase to use it instead of `w_msquic_api`: #12

**Comment by cthulhu-irl** [comment]
@PooyaEimandar the quic wrapper leak was fixed by #12 merge.
